-------------------------------------------------------------------------------
-- (c) copyright capgemini
-- file name:               PJ_EC_SALES_GMV_TMP_INIT.sql
-- source table:            
-- target table:            
-- project:
-- note:
-- purpose:                 pj_ec_sales_gmv_tmp生成数据
--=============================================================================
-- creation date:       2019-3-7
-- origin author:       capgemini
--no
-- version: %1.0%
--
-- modification history
-- --------------------
-- date         byperson        description
-- ----------   --------------  -----------------------------------------------
-- 2019-3-7  capgemini       
-------------------------------------------------------------------------------
set parquet.compression=GZIP;
set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.max.dynamic.partitions.pernode=10000;
insert overwrite table bigdata_dm.pj_ec_sales_gmv_tmp partition(date_)
select 
a.sales_dt_wid,
a.bg_wid,
a.platform_name,
a.sale_area_name,
a.dealer_wid,
a.erp_id,
a.pro_id,
a.pro_categ_name,
a.pro_brand_name,
case when a.pro_grade='无' or a.pro_grade='未定义'  or a.pro_grade ='缺省' or  a.pro_grade ='-1' then '空' else a.pro_grade end pro_grade,
a.site_wid,
max(a.w_insert_dt) as w_insert_dt,
sum(a.sales_qty_ton) as sales_qty_ton,
sum(a.sales_qty_box) as sales_qty_box,
sum(a.sales_amt_before) as sales_amt_before,
sum(a.sales_amt_after) as sales_amt_after,
sum(a.amt_bf_without_tax) as amt_bf_without_tax,
sum(a.amt_af_without_tax) as amt_af_without_tax,
sum(a.plan_qty_ton) as plan_qty_ton,
sum(a.plan_qty_box) as plan_qty_box,
sum(a.plan_amt_bf_without_tax) as plan_amt_bf_without_tax,
sum(a.plan_amt_af_without_tax) as plan_amt_af_without_tax,
sum(a.task_qty_ton) as task_qty_ton,
sum(a.task_qty_box) as task_qty_box,
sum(a.task_amt_bf_without_tax) as task_amt_bf_without_tax,
sum(a.task_amt_af_without_tax) as task_amt_af_without_tax,
sum(a.budget_qty_ton) as budget_qty_ton,
sum(a.budget_qty_box) as budget_qty_box,
sum(a.budget_amt_bf_without_tax) as budget_amt_bf_without_tax,
sum(a.budget_amt_af_without_tax) as budget_amt_af_without_tax,
sum(a.plan_amt_before) as plan_amt_before,
sum(a.plan_amt_after) as plan_amt_after,
sum(a.task_amt_before) as task_amt_before,
sum(a.task_amt_after) as task_amt_after,
sum(a.budget_amt_before) as budget_amt_before,
sum(a.budget_amt_after) as budget_amt_after,
a.sales_year,
a.date_
from 
(select 
nvl(t3.row_wid,-1) as sales_dt_wid,
3 as bg_wid,
nvl(t5.platform_name,'-1') as platform_name,
nvl(t5.sale_area_name,'-1') as sale_area_name,
-1 as dealer_wid,
nvl(t4.erp_id,'-1') as erp_id,
t2.pro_id as pro_id,
nvl(t4.pro_categ_name,'-1') as pro_categ_name,
nvl(t4.pro_brand_name,'-1') as pro_brand_name,
nvl(t4.pro_grade,'-1') as pro_grade,
-1 as site_wid,
current_date as w_insert_dt,
0 as sales_qty_ton,
cast(t2.sales_qty_box as BIGINT) as sales_qty_box,
cast(t2.sales_amt_before as BIGINT) as sales_amt_before,
0 sales_amt_after,
0 as amt_bf_without_tax,
0 as amt_af_without_tax,
0 as plan_qty_ton,
0 as plan_qty_box,
0 as plan_amt_bf_without_tax,
0 as plan_amt_af_without_tax,
0 as task_qty_ton,
0 as task_qty_box,
0 as task_amt_bf_without_tax,
0 as task_amt_af_without_tax,
0 as budget_qty_ton,
0 as budget_qty_box,
0 as budget_amt_bf_without_tax,
0 as budget_amt_af_without_tax,
0 as plan_amt_before,
0 as plan_amt_after,
0 as task_amt_before,
0 as task_amt_after,
0 as budget_amt_before,
0 as budget_amt_after,
nvl(substr(t3.row_wid,1,4),-1) as sales_year,
nvl(substr(t3.row_wid,1,6),'-1') as date_
from
(select 
t4.pro_id,
t4.sales_qty_box,
t4.sales_amt_before,
t4.stats_dt,
t4.sale_area_name
from
(
select
nvl(if(trim(t.pro_id)='',null,trim(t.pro_id)),'-1')   as pro_id,
cast(nvl(if(trim(t.deal_qty)='',null,trim(t.deal_qty)),0)  as bigint) as sales_qty_box,
cast(nvl(if(trim(t.deal_amt)='',null,trim(t.deal_amt)),0)  as bigint) as sales_amt_before,
t.stats_dt,
nvl(if(trim(t.store_nm)='',null,trim(t.store_nm)),'-1')  as sale_area_name,
case when t1.sku_id is null and cast(nvl(if(trim(t.deal_amt)='',null,trim(t.deal_amt)),0)  as bigint)=0 then 0
when nvl(cast(nvl(if(trim(t.deal_qty)='',null,trim(t.deal_qty)),0)  as bigint),0) =0 and nvl(cast(nvl(if(trim(t.deal_amt)='',null,trim(t.deal_amt)),0)  as bigint),0) =0
then 0 else 1 end as flag
from datalake_md.fact_ec_chan_sale_dtl t
 left join bigdata_dw.w_ec_product_d t1 on trim(t.pro_id) = t1.sku_id and t1.dual_='1'
where t.stats_dt is not null and t.stats_dt >='20180101'
) t4
where flag =1
) t2
left join bigdata_dw.w_date_d t3 on t2.stats_dt = t3.row_wid and t3.dt_type = 'D'
left join bigdata_dw.w_ec_product_d t4 on trim(t2.pro_id) = t4.sku_id and t4.dual_ in ('0','1')
left join (select  platform_name,sale_area_name as sale_area_name1 ,final_name as sale_area_name from bigdata_dw.w_ec_area_d_tmp where platform_type = 'GMV') t5 on t2.sale_area_name = t5.sale_area_name1) a
group by 
a.sales_dt_wid,
a.bg_wid,
a.platform_name,
a.sale_area_name,
a.dealer_wid,
a.erp_id,
a.pro_id,
a.pro_categ_name,
a.pro_brand_name,
a.pro_grade,
a.site_wid,
a.sales_year,
a.date_

union all

select
d.day_id as sales_dt_wid,
3 as bg_wid,
c.platform_name,
c.sale_area_name,
-1 as dealer_wid,
'-1' as erp_id,
'-1' as pro_id,
b.pro_categ_name,
'-1' as pro_brand_name,
'空' as pro_grade,
-1 as site_wid,
current_date as w_insert_dt,
0 sales_qty_ton,
0 sales_qty_box,
0 sales_amt_before,
0 sales_amt_after,
0 amt_bf_without_tax,
0 amt_af_without_tax,
0 plan_qty_ton,
0 plan_qty_box,
0 plan_amt_bf_without_tax,
0 plan_amt_af_without_tax,
0 task_qty_ton,
0 task_qty_box,
0 task_amt_bf_without_tax,
0 task_amt_af_without_tax,
0 budget_qty_ton,
0 budget_qty_box,
0 budget_amt_bf_without_tax,
0 budget_amt_af_without_tax,
0 plan_amt_before,
0 plan_amt_after,
if(substr(d.day_id,7,2)='01',b.task_amt_before,0) as task_amt_before,
0 task_amt_after,
0 budget_amt_before,
0 budget_amt_after,
substr(b.mon_id,1,4) as sales_year,
b.mon_id as date_
from (select row_wid day_id from bigdata_dw.w_date_d where dt_type='D' and row_wid>=cast('20180101' as bigint) and row_wid<=cast(concat(substr(date_sub(current_date,1),1,4),'1231') as bigint)) d
left join (select 
area as sale_area_name,
prod_desc as pro_categ_name,
year_month as mon_id,
cast(if(tax_amt='',0,nvl(tax_amt,0)) as bigint) as task_amt_before
from datalake_md.fact_ec_budget_plan where src_identity='GMV' and year_month >='201801' and year_month <=concat(substr(date_sub(current_date,1),1,4),'12')) b
on substr(d.day_id,1,6) = b.mon_id
left join (select  platform_name,sale_area_name as sale_area_name1 ,final_name as sale_area_name from bigdata_dw.w_ec_area_d_tmp where platform_type = 'GMV') c
on b.sale_area_name = c.sale_area_name1
where b.mon_id is not null;


insert overwrite table bigdata_dm.pj_ec_sales_gmv_ago partition(date_)
select
t.sales_dt_wid,
t.bg_wid,
t.platform_name,
t.sale_area_name,
t.dealer_wid,
t.erp_id,
t.pro_id,
t.pro_categ_name,
t.pro_brand_name,
t.pro_grade,
t.site_wid,
sum(nvl(sales_qty_ton,0)) sales_qty_ton,
sum(nvl(sales_qty_box,0)) sales_qty_box,
sum(nvl(sales_amt_before,0))  sales_amt_before,
sum(nvl(sales_amt_after,0)) sales_amt_after,
sum(nvl(amt_bf_without_tax,0))  amt_bf_without_tax,
sum(nvl(amt_af_without_tax,0))  amt_af_without_tax,
sum(nvl(plan_qty_ton,0))  plan_qty_ton,
sum(nvl(plan_qty_box,0))  plan_qty_box,
sum(nvl(plan_amt_bf_without_tax,0)) plan_amt_bf_without_tax,
sum(nvl(plan_amt_af_without_tax,0)) plan_amt_af_without_tax,
sum(nvl(task_qty_ton,0))  task_qty_ton,
sum(nvl(task_qty_box,0))  task_qty_box,
sum(nvl(task_amt_bf_without_tax,0)) task_amt_bf_without_tax,
sum(nvl(task_amt_af_without_tax,0)) task_amt_af_without_tax,
sum(nvl(budget_qty_ton,0))  budget_qty_ton,
sum(nvl(budget_qty_box,0))  budget_qty_box,
sum(nvl(budget_amt_bf_without_tax,0)) budget_amt_bf_without_tax,
sum(nvl(budget_amt_af_without_tax,0)) budget_amt_af_without_tax,
sum(nvl(plan_amt_before,0)) plan_amt_before,
sum(nvl(plan_amt_after,0))  plan_amt_after,
sum(nvl(task_amt_before,0)) task_amt_before,
sum(nvl(task_amt_after,0))  task_amt_after,
sum(nvl(budget_amt_before,0)) budget_amt_before,
sum(nvl(budget_amt_after,0))  budget_amt_after,
sum(nvl(mago_sales_qty_ton,0))  mago_sales_qty_ton,
sum(nvl(mago_sales_qty_box,0))  mago_sales_qty_box,
sum(nvl(mago_amt_before,0)) mago_amt_before,
sum(nvl(mago_amt_bf_without_tax,0)) mago_amt_bf_without_tax,
sum(nvl(mago_amt_after,0))  mago_amt_after,
sum(nvl(mago_amt_af_without_tax,0)) mago_amt_af_without_tax,
sum(nvl(mago_plan_amt_before,0))  mago_plan_amt_before,
sum(nvl(mago_plan_amt_after,0)) mago_plan_amt_after,
sum(nvl(mago_task_amt_before,0))  mago_task_amt_before,
sum(nvl(mago_task_amt_after,0)) mago_task_amt_after,
sum(nvl(mago_budget_amt_before,0))  mago_budget_amt_before,
sum(nvl(mago_budget_amt_after,0)) mago_budget_amt_after,
sum(nvl(tmago_sales_qty_ton,0)) tmago_sales_qty_ton,
sum(nvl(tmago_sales_qty_box,0)) tmago_sales_qty_box,
sum(nvl(tmago_sales_amt_before,0))  tmago_sales_amt_before,
sum(nvl(tmago_sales_amt_after,0)) tmago_sales_amt_after,
sum(nvl(tmago_amt_bf_without_tax,0))  tmago_amt_bf_without_tax,
sum(nvl(tmago_amt_af_without_tax,0))  tmago_amt_af_without_tax,
sum(nvl(tmago_plan_amt_before,0)) tmago_plan_amt_before,
sum(nvl(tmago_plan_amt_after,0))  tmago_plan_amt_after,
sum(nvl(tmago_task_amt_before,0)) tmago_task_amt_before,
sum(nvl(tmago_task_amt_after,0))  tmago_task_amt_after,
sum(nvl(tmago_budget_amt_before,0)) tmago_budget_amt_before,
sum(nvl(tmago_budget_amt_after,0))  tmago_budget_amt_after,
sum(nvl(yago_sales_qty_ton,0))  yago_sales_qty_ton,
sum(nvl(yago_sales_qty_box,0))  yago_sales_qty_box,
sum(nvl(yago_amt_before,0)) yago_amt_before,
sum(nvl(yago_amt_bf_without_tax,0)) yago_amt_bf_without_tax,
sum(nvl(yago_amt_after,0))  yago_amt_after,
sum(nvl(yago_amt_af_without_tax,0)) yago_amt_af_without_tax,
sum(nvl(yago_plan_qty_ton,0)) yago_plan_qty_ton,
sum(nvl(yago_plan_qty_box,0)) yago_plan_qty_box,
sum(nvl(yago_plan_amt_bf_no_tax,0)) yago_plan_amt_bf_no_tax,
sum(nvl(yago_plan_amt_af_no_tax,0)) yago_plan_amt_af_no_tax,
sum(nvl(yago_task_qty_ton,0)) yago_task_qty_ton,
sum(nvl(yago_task_qty_box,0)) yago_task_qty_box,
sum(nvl(yago_task_amt_bf_no_tax,0)) yago_task_amt_bf_no_tax,
sum(nvl(yago_task_amt_af_no_tax,0)) yago_task_amt_af_no_tax,
sum(nvl(yago_budget_qty_ton,0)) yago_budget_qty_ton,
sum(nvl(yago_budget_qty_box,0)) yago_budget_qty_box,
sum(nvl(yago_budget_amt_bf_without_tax,0))  yago_budget_amt_bf_without_tax,
sum(nvl(yago_budget_amt_af_without_tax,0))  yago_budget_amt_af_without_tax,
sum(nvl(yago_plan_amt_before,0))  yago_plan_amt_before,
sum(nvl(yago_plan_amt_after,0)) yago_plan_amt_after,
sum(nvl(yago_task_amt_before,0))  yago_task_amt_before,
sum(nvl(yago_task_amt_after,0)) yago_task_amt_after,
sum(nvl(yago_budget_amt_before,0))  yago_budget_amt_before,
sum(nvl(yago_budget_amt_after,0)) yago_budget_amt_after,
substr(t.sales_dt_wid,1,6)
from
(select
sales_dt_wid,
bg_wid,
platform_name,
sale_area_name,
dealer_wid,
erp_id,
pro_id,
pro_categ_name,
pro_brand_name,
pro_grade,
site_wid,
sales_qty_ton,
sales_qty_box,
sales_amt_before,
sales_amt_after,
amt_bf_without_tax,
amt_af_without_tax,
plan_qty_ton,
plan_qty_box,
plan_amt_bf_without_tax,
plan_amt_af_without_tax,
task_qty_ton,
task_qty_box,
task_amt_bf_without_tax,
task_amt_af_without_tax,
budget_qty_ton,
budget_qty_box,
budget_amt_bf_without_tax,
budget_amt_af_without_tax,
plan_amt_before,
plan_amt_after,
task_amt_before,
task_amt_after,
budget_amt_before,
budget_amt_after,
0 mago_sales_qty_ton,
0 mago_sales_qty_box,
0 mago_amt_before,
0 mago_amt_bf_without_tax,
0 mago_amt_after,
0 mago_amt_af_without_tax,
0 mago_plan_amt_before,
0 mago_plan_amt_after,
0 mago_task_amt_before,
0 mago_task_amt_after,
0 mago_budget_amt_before,
0 mago_budget_amt_after,
0 tmago_sales_qty_ton,
0 tmago_sales_qty_box,
0 tmago_sales_amt_before,
0 tmago_sales_amt_after,
0 tmago_amt_bf_without_tax,
0 tmago_amt_af_without_tax,
0 tmago_plan_amt_before,
0 tmago_plan_amt_after,
0 tmago_task_amt_before,
0 tmago_task_amt_after,
0 tmago_budget_amt_before,
0 tmago_budget_amt_after,
0 yago_sales_qty_ton,
0 yago_sales_qty_box,
0 yago_amt_before,
0 yago_amt_bf_without_tax,
0 yago_amt_after,
0 yago_amt_af_without_tax,
0 yago_plan_qty_ton,
0 yago_plan_qty_box,
0 yago_plan_amt_bf_no_tax,
0 yago_plan_amt_af_no_tax,
0 yago_task_qty_ton,
0 yago_task_qty_box,
0 yago_task_amt_bf_no_tax,
0 yago_task_amt_af_no_tax,
0 yago_budget_qty_ton,
0 yago_budget_qty_box,
0 yago_budget_amt_bf_without_tax,
0 yago_budget_amt_af_without_tax,
0 yago_plan_amt_before,
0 yago_plan_amt_after,
0 yago_task_amt_before,
0 yago_task_amt_after,
0 yago_budget_amt_before,
0 yago_budget_amt_after
from bigdata_dm.pj_ec_sales_gmv_tmp
where date_>='201801'

union all

select
cast(regexp_replace(add_months(concat_ws('-',substr(mago.sales_dt_wid,1,4),substr(mago.sales_dt_wid,5,2),substr(mago.sales_dt_wid,7,2)),1),'-','') as bigint) as sales_dt_wid,
mago.bg_wid,
mago.platform_name,
mago.sale_area_name,
mago.dealer_wid,
mago.erp_id,
mago.pro_id,
mago.pro_categ_name,
mago.pro_brand_name,
mago.pro_grade,
mago.site_wid,
0 sales_qty_ton,
0 sales_qty_box,
0 sales_amt_before,
0 sales_amt_after,
0 amt_bf_without_tax,
0 amt_af_without_tax,
0 plan_qty_ton,
0 plan_qty_box,
0 plan_amt_bf_without_tax,
0 plan_amt_af_without_tax,
0 task_qty_ton,
0 task_qty_box,
0 task_amt_bf_without_tax,
0 task_amt_af_without_tax,
0 budget_qty_ton,
0 budget_qty_box,
0 budget_amt_bf_without_tax,
0 budget_amt_af_without_tax,
0 plan_amt_before,
0 plan_amt_after,
0 task_amt_before,
0 task_amt_after,
0 budget_amt_before,
0 budget_amt_after,
mago.sales_qty_ton as mago_sales_qty_ton,
mago.sales_qty_box as mago_sales_qty_box,
mago.sales_amt_before as mago_amt_before,
mago.amt_bf_without_tax as mago_amt_bf_without_tax,
mago.sales_amt_after as mago_amt_after,
mago.amt_af_without_tax as mago_amt_af_without_tax,
mago.plan_amt_before as mago_plan_amt_before,
mago.plan_amt_after as mago_plan_amt_after,
mago.task_amt_before as mago_task_amt_before,
mago.task_amt_after as mago_task_amt_after,
mago.budget_amt_before as mago_budget_amt_before,
mago.budget_amt_after as mago_budget_amt_after,
0 tmago_sales_qty_ton,
0 tmago_sales_qty_box,
0 tmago_sales_amt_before,
0 tmago_sales_amt_after,
0 tmago_amt_bf_without_tax,
0 tmago_amt_af_without_tax,
0 tmago_plan_amt_before,
0 tmago_plan_amt_after,
0 tmago_task_amt_before,
0 tmago_task_amt_after,
0 tmago_budget_amt_before,
0 tmago_budget_amt_after,
0 yago_sales_qty_ton,
0 yago_sales_qty_box,
0 yago_amt_before,
0 yago_amt_bf_without_tax,
0 yago_amt_after,
0 yago_amt_af_without_tax,
0 yago_plan_qty_ton,
0 yago_plan_qty_box,
0 yago_plan_amt_bf_no_tax,
0 yago_plan_amt_af_no_tax,
0 yago_task_qty_ton,
0 yago_task_qty_box,
0 yago_task_amt_bf_no_tax,
0 yago_task_amt_af_no_tax,
0 yago_budget_qty_ton,
0 yago_budget_qty_box,
0 yago_budget_amt_bf_without_tax,
0 yago_budget_amt_af_without_tax,
0 yago_plan_amt_before,
0 yago_plan_amt_after,
0 yago_task_amt_before,
0 yago_task_amt_after,
0 yago_budget_amt_before,
0 yago_budget_amt_after
from bigdata_dm.pj_ec_sales_gmv_tmp mago
where mago.date_>='201801' and add_months(concat_ws('-',substr(mago.sales_dt_wid,1,4),substr(mago.sales_dt_wid,5,2),substr(mago.sales_dt_wid,7,2)),1)<current_date()

union all

select
cast(regexp_replace(add_months(concat_ws('-',substr(tmago.sales_dt_wid,1,4),substr(tmago.sales_dt_wid,5,2),substr(tmago.sales_dt_wid,7,2)),3),'-','') as bigint) as sales_dt_wid,
tmago.bg_wid,
tmago.platform_name,
tmago.sale_area_name,
tmago.dealer_wid,
tmago.erp_id,
tmago.pro_id,
tmago.pro_categ_name,
tmago.pro_brand_name,
tmago.pro_grade,
tmago.site_wid,
0 sales_qty_ton,
0 sales_qty_box,
0 sales_amt_before,
0 sales_amt_after,
0 amt_bf_without_tax,
0 amt_af_without_tax,
0 plan_qty_ton,
0 plan_qty_box,
0 plan_amt_bf_without_tax,
0 plan_amt_af_without_tax,
0 task_qty_ton,
0 task_qty_box,
0 task_amt_bf_without_tax,
0 task_amt_af_without_tax,
0 budget_qty_ton,
0 budget_qty_box,
0 budget_amt_bf_without_tax,
0 budget_amt_af_without_tax,
0 plan_amt_before,
0 plan_amt_after,
0 task_amt_before,
0 task_amt_after,
0 budget_amt_before,
0 budget_amt_after,
0 mago_sales_qty_ton,
0 mago_sales_qty_box,
0 mago_amt_before,
0 mago_amt_bf_without_tax,
0 mago_amt_after,
0 mago_amt_af_without_tax,
0 mago_plan_amt_before,
0 mago_plan_amt_after,
0 mago_task_amt_before,
0 mago_task_amt_after,
0 mago_budget_amt_before,
0 mago_budget_amt_after,
tmago.sales_qty_ton as tmago_sales_qty_ton,
tmago.sales_qty_box as tmago_sales_qty_box,
tmago.sales_amt_before as tmago_sales_amt_before,
tmago.sales_amt_after as tmago_sales_amt_after,
tmago.amt_bf_without_tax as tmago_amt_bf_without_tax,
tmago.amt_af_without_tax as tmago_amt_af_without_tax,
tmago.plan_amt_before as tmago_plan_amt_before,
tmago.plan_amt_after as tmago_plan_amt_after,
tmago.task_amt_before as tmago_task_amt_before,
tmago.task_amt_after as tmago_task_amt_after,
tmago.budget_amt_before as tmago_budget_amt_before,
tmago.budget_amt_after as tmago_budget_amt_after,
0 yago_sales_qty_ton,
0 yago_sales_qty_box,
0 yago_amt_before,
0 yago_amt_bf_without_tax,
0 yago_amt_after,
0 yago_amt_af_without_tax,
0 yago_plan_qty_ton,
0 yago_plan_qty_box,
0 yago_plan_amt_bf_no_tax,
0 yago_plan_amt_af_no_tax,
0 yago_task_qty_ton,
0 yago_task_qty_box,
0 yago_task_amt_bf_no_tax,
0 yago_task_amt_af_no_tax,
0 yago_budget_qty_ton,
0 yago_budget_qty_box,
0 yago_budget_amt_bf_without_tax,
0 yago_budget_amt_af_without_tax,
0 yago_plan_amt_before,
0 yago_plan_amt_after,
0 yago_task_amt_before,
0 yago_task_amt_after,
0 yago_budget_amt_before,
0 yago_budget_amt_after
from bigdata_dm.pj_ec_sales_gmv_tmp tmago
where tmago.date_>='201801' and add_months(concat_ws('-',substr(tmago.sales_dt_wid,1,4),substr(tmago.sales_dt_wid,5,2),substr(tmago.sales_dt_wid,7,2)),3)<current_date()

union all

select
cast(regexp_replace(add_months(concat_ws('-',substr(yago.sales_dt_wid,1,4),substr(yago.sales_dt_wid,5,2),substr(yago.sales_dt_wid,7,2)),12),'-','') as bigint) as sales_dt_wid,
yago.bg_wid,
yago.platform_name,
yago.sale_area_name,
yago.dealer_wid,
yago.erp_id,
yago.pro_id,
yago.pro_categ_name,
yago.pro_brand_name,
yago.pro_grade,
yago.site_wid,
0 sales_qty_ton,
0 sales_qty_box,
0 sales_amt_before,
0 sales_amt_after,
0 amt_bf_without_tax,
0 amt_af_without_tax,
0 plan_qty_ton,
0 plan_qty_box,
0 plan_amt_bf_without_tax,
0 plan_amt_af_without_tax,
0 task_qty_ton,
0 task_qty_box,
0 task_amt_bf_without_tax,
0 task_amt_af_without_tax,
0 budget_qty_ton,
0 budget_qty_box,
0 budget_amt_bf_without_tax,
0 budget_amt_af_without_tax,
0 plan_amt_before,
0 plan_amt_after,
0 task_amt_before,
0 task_amt_after,
0 budget_amt_before,
0 budget_amt_after,
0 mago_sales_qty_ton,
0 mago_sales_qty_box,
0 mago_amt_before,
0 mago_amt_bf_without_tax,
0 mago_amt_after,
0 mago_amt_af_without_tax,
0 mago_plan_amt_before,
0 mago_plan_amt_after,
0 mago_task_amt_before,
0 mago_task_amt_after,
0 mago_budget_amt_before,
0 mago_budget_amt_after,
0 tmago_sales_qty_ton,
0 tmago_sales_qty_box,
0 tmago_sales_amt_before,
0 tmago_sales_amt_after,
0 tmago_amt_bf_without_tax,
0 tmago_amt_af_without_tax,
0 tmago_plan_amt_before,
0 tmago_plan_amt_after,
0 tmago_task_amt_before,
0 tmago_task_amt_after,
0 tmago_budget_amt_before,
0 tmago_budget_amt_after,
yago.sales_qty_ton as yago_sales_qty_ton,
yago.sales_qty_box as yago_sales_qty_box,
yago.sales_amt_before as yago_amt_before,
yago.amt_bf_without_tax as yago_amt_bf_without_tax,
yago.sales_amt_after as yago_amt_after,
yago.amt_af_without_tax as yago_amt_af_without_tax,
yago.plan_qty_ton as yago_plan_qty_ton,
yago.plan_qty_box as yago_plan_qty_box,
0 yago_plan_amt_bf_no_tax,
0 yago_plan_amt_af_no_tax,
yago.task_qty_ton as yago_task_qty_ton,
yago.task_qty_box as yago_task_qty_box,
0 yago_task_amt_bf_no_tax,
0 yago_task_amt_af_no_tax,
yago.budget_qty_ton as yago_budget_qty_ton,
yago.budget_qty_box as yago_budget_qty_box,
yago.budget_amt_bf_without_tax as yago_budget_amt_bf_without_tax,
yago.budget_amt_af_without_tax as yago_budget_amt_af_without_tax,
yago.plan_amt_before as yago_plan_amt_before,
yago.plan_amt_after as yago_plan_amt_after,
yago.task_amt_before as yago_task_amt_before,
yago.task_amt_after as yago_task_amt_after,
yago.budget_amt_before as yago_budget_amt_before,
yago.budget_amt_after as yago_budget_amt_after
from bigdata_dm.pj_ec_sales_gmv_tmp yago
where yago.date_>='201801' and add_months(concat_ws('-',substr(yago.sales_dt_wid,1,4),substr(yago.sales_dt_wid,5,2),substr(yago.sales_dt_wid,7,2)),12)<current_date()
) t
group by
t.sales_dt_wid,
t.bg_wid,
t.platform_name,
t.sale_area_name,
t.dealer_wid,
t.erp_id,
t.pro_id,
t.pro_categ_name,
t.pro_brand_name,
t.pro_grade,
t.site_wid;