

--逻辑语句
insert overwrite table bigdata_dm.fact_tpm_cost_ytd
select
bg_wid,
bg_name,
bug_month,
area_name,
region_name,
camp_type_name,
exp_subj_name,
function_type_name,
exp_from_name,
dep_name,
dealer_id,
dealer_name,
is_direct,
system_name,
sum(case when dt_type='M' then sales_cost else 0 end ) sales_cost,
sum(case when dt_type='M' then zxje else 0 end ) zxje,
sum(case when dt_type='M' then xzj else 0 end ) xzj,
sum(case when dt_type='M' then cost_budget_year else 0 end ) cost_budget_year,
sum(case when dt_type='M' then sales_cost_lm else 0 end ) sales_cost_lm,
sum(case when dt_type='M' then zxje_lm else 0 end ) zxje_lm,
sum(case when dt_type='M' then xzj_lm else 0 end ) xzj_lm,
sum(case when dt_type='M' then cost_budget_year_lm else 0 end ) cost_budget_year_lm,
sum(case when dt_type='M' then sales_cost_ly else 0 end ) sales_cost_ly,
sum(case when dt_type='M' then zxje_ly else 0 end ) zxje_ly,
sum(case when dt_type='M' then xzj_ly else 0 end ) xzj_ly,
sum(case when dt_type='M' then cost_budget_year_ly else 0 end ) cost_budget_year_ly,
sum(case when dt_type='YTD' then sales_cost else 0 end ) sales_cost_ytd,
sum(case when dt_type='YTD' then zxje else 0 end ) zxje_ytd,
sum(case when dt_type='YTD' then xzj else 0 end ) xzj_ytd,
sum(case when dt_type='YTD' then cost_budget_year else 0 end ) cost_budget_year_ytd,
sum(case when dt_type='YTD' then sales_cost_lm else 0 end ) sales_cost_lm_ytd,
sum(case when dt_type='YTD' then zxje_lm else 0 end ) zxje_lm_ytd,
sum(case when dt_type='YTD' then xzj_lm else 0 end ) xzj_lm_ytd,
sum(case when dt_type='YTD' then cost_budget_year_lm else 0 end ) cost_budget_year_lm_ytd,
sum(case when dt_type='YTD' then sales_cost_ly else 0 end ) sales_cost_ly_ytd,
sum(case when dt_type='YTD' then zxje_ly else 0 end ) zxje_ly_ytd,
sum(case when dt_type='YTD' then xzj_ly else 0 end ) xzj_ly_ytd,
sum(case when dt_type='YTD' then cost_budget_year_ly else 0 end ) cost_budget_year_ly_ytd
from 
(
select
bg_wid,
bg_name,
bug_month,
area_name,
region_name,
camp_type_name,
exp_subj_name,
function_type_name,
exp_from_name,
dep_name,
dealer_id,
dealer_name,
is_direct,
system_name,
'M' dt_type,
sales_cost,
zxje,
xzj,
cost_budget_year,
sales_cost_lm,
zxje_lm,
xzj_lm,
cost_budget_year_lm,
sales_cost_ly,
zxje_ly,
xzj_ly,
cost_budget_year_ly
from bigdata_dm.fact_tpm_cost_yago
union all
select
bg_wid,
bg_name,
t1.day_id bug_month,
area_name,
region_name,
camp_type_name,
exp_subj_name,
function_type_name,
exp_from_name,
dep_name,
dealer_id,
dealer_name,
is_direct,
system_name,
'YTD' dt_type,
sales_cost,
zxje,
xzj,
cost_budget_year,
sales_cost_lm,
zxje_lm,
xzj_lm,
cost_budget_year_lm,
sales_cost_ly,
zxje_ly,
xzj_ly,
cost_budget_year_ly
from (select row_wid day_id,floor(row_wid/100)*100+1 ytd_id from bigdata_dw.w_date_d where dt_type='M' and row_wid>=201701 and row_wid<=cast(date_format(current_date,'yyyyMM') as bigint)) t1
left join bigdata_dm.fact_tpm_cost_yago t2
on  t2.bug_month>=t1.ytd_id 
and t2.bug_month<=t1.day_id
) T
group by 
bg_wid,
bg_name,
bug_month,
area_name,
region_name,
camp_type_name,
exp_subj_name,
function_type_name,
exp_from_name,
dep_name,
dealer_id,
dealer_name,
is_direct,
system_name
;

