-------------------------------------------------------------------------------
-- (c) copyright capgemini
-- file name:               PJ_SALES_MTD_TMP_INC.sql
-- source table:            pj_sales_rate_daily_tmp
-- target table:            bigdata_dm.pj_sales_daily_tmp
-- project:
-- note:
-- purpose:                 销售日报月累计报表
--=============================================================================
-- creation date:       2018-10-21
-- origin author:       capgemini
--no
-- version: %1.0%
--
-- modification history
-- --------------------
-- date         byperson        description
-- ----------   --------------  -----------------------------------------------
-- 2018-10-21   capgemini       pj_sales_daily_tmp
-------------------------------------------------------------------------------
set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.max.dynamic.partitions.pernode=10000;
SET parquet.compression=GZIP;
insert overwrite table bigdata_dm.pj_ec_sales_gmv_mtd_tmp partition(date_)
select 
sales_dt_wid,
bg_wid,
platform_name,
sale_area_name,
dealer_wid,
erp_id,
pro_id,
pro_categ_name,
pro_brand_name,
pro_grade,
site_wid,
from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss')  as w_insert_dt,
0 price_before,
0 price_after,
sales_qty_ton,
sales_qty_ton_mtd,
0 sales_qty_ton_ytd,
sales_qty_box,
sales_qty_box_mtd,
0 sales_qty_box_ytd,
sales_amt_before,
sales_amt_before_mtd,
0 sales_amt_before_ytd,
sales_amt_after,
sales_amt_after_mtd,
0 sales_amt_after_ytd,
amt_bf_without_tax,
amt_bf_without_tax_mtd,
0 amt_bf_without_tax_ytd,
amt_af_without_tax,
amt_af_without_tax_mtd,
0 amt_af_without_tax_ytd,
plan_qty_ton,
plan_qty_ton_mtd,
0 plan_qty_ton_ytd,
plan_qty_box,
plan_qty_box_mtd,
0 plan_qty_box_ytd,
plan_amt_bf_without_tax,
plan_amt_bf_without_tax_mtd,
0 plan_amt_bf_without_tax_ytd,
plan_amt_af_without_tax,
plan_amt_af_without_tax_mtd,
0 plan_amt_af_without_tax_ytd,
task_qty_ton,
task_qty_ton_mtd,
0 task_qty_ton_ytd,
0 task_qty_ton_ytd_all,
task_qty_box,
task_qty_box_mtd,
0 task_qty_box_ytd,
0 task_qty_box_ytd_all,
task_amt_bf_without_tax,
task_amt_bf_without_tax_mtd,
0 task_amt_bf_without_tax_ytd,
0 task_amt_bf_without_tax_ytd_all,
task_amt_af_without_tax,
task_amt_af_without_tax_mtd,
0 task_amt_af_without_tax_ytd,
0 task_amt_af_without_tax_ytd_all,
budget_qty_ton,
budget_qty_ton_mtd,
0 budget_qty_ton_ytd,
0 budget_qty_ton_ytd_all,
budget_qty_box,
budget_qty_box_mtd,
0 budget_qty_box_ytd,
0 budget_qty_box_ytd_all,
budget_amt_bf_without_tax,
budget_amt_bf_without_tax_mtd,
0 budget_amt_bf_without_tax_ytd,
0 budget_amt_bf_without_tax_ytd_all,
budget_amt_af_without_tax,
budget_amt_af_without_tax_mtd,
0 budget_amt_af_without_tax_ytd,
0 budget_amt_af_without_tax_ytd_all,
mago_sales_qty_ton,
mago_sales_qty_ton_mtd,
0 mago_sales_qty_ton_ytd,
mago_sales_qty_box,
mago_sales_qty_box_mtd,
0 mago_sales_qty_box_ytd,
mago_amt_before,
mago_amt_before_mtd,
0 mago_amt_before_ytd,
mago_amt_bf_without_tax,
mago_amt_bf_without_tax_mtd,
0 mago_amt_bf_without_tax_ytd,
mago_amt_after,
mago_amt_after_mtd,
0 mago_amt_after_ytd,
mago_amt_af_without_tax,
mago_amt_af_without_tax_mtd,
0 mago_amt_af_without_tax_ytd,
yago_sales_qty_ton,
yago_sales_qty_ton_mtd,
0 yago_sales_qty_ton_ytd,
yago_sales_qty_box,
yago_sales_qty_box_mtd,
0 yago_sales_qty_box_ytd,
yago_amt_before,
yago_amt_before_mtd,
0 yago_amt_before_ytd,
yago_amt_bf_without_tax,
yago_amt_bf_without_tax_mtd,
0 yago_amt_bf_without_tax_ytd,
yago_amt_after,
yago_amt_after_mtd,
0 yago_amt_after_ytd,
yago_amt_af_without_tax,
yago_amt_af_without_tax_mtd,
0 yago_amt_af_without_tax_ytd,
yago_plan_qty_ton,
yago_plan_qty_ton_mtd,
0 yago_plan_qty_ton_ytd,
yago_plan_qty_box,
yago_plan_qty_box_mtd,
0 yago_plan_qty_box_ytd,
yago_plan_amt_bf_no_tax,
yago_plan_amt_bf_no_tax_mtd,
0 yago_plan_amt_bf_no_tax_ytd,
yago_plan_amt_af_no_tax,
yago_plan_amt_af_no_tax_mtd,
0 yago_plan_amt_af_no_tax_ytd,
yago_task_qty_ton,
yago_task_qty_ton_mtd,
0 yago_task_qty_ton_ytd,
0 yago_task_qty_ton_ytd_all,
yago_task_qty_box,
yago_task_qty_box_mtd,
0 yago_task_qty_box_ytd,
0 yago_task_qty_box_ytd_all,
yago_task_amt_bf_no_tax,
yago_task_amt_bf_no_tax_mtd,
0 yago_task_amt_bf_no_tax_ytd,
0 yago_task_amt_bf_no_tax_ytd_all,
yago_task_amt_af_no_tax,
yago_task_amt_af_no_tax_mtd,
0 yago_task_amt_af_no_tax_ytd,
0 yago_task_amt_af_no_tax_ytd_all,
yago_budget_qty_ton,
yago_budget_qty_ton_mtd,
0 yago_budget_qty_ton_ytd,
0 yago_budget_qty_ton_ytd_all,
yago_budget_qty_box,
yago_budget_qty_box_mtd,
0 yago_budget_qty_box_ytd,
0 yago_budget_qty_box_ytd_all,
yago_budget_amt_bf_without_tax,
yago_budget_amt_bf_without_tax_mtd,
0 yago_budget_amt_bf_without_tax_ytd,
0 yago_budget_amt_bf_without_tax_ytd_all,
yago_budget_amt_af_without_tax,
yago_budget_amt_af_without_tax_mtd,
0 yago_budget_amt_af_without_tax_ytd,
0 yago_budget_amt_af_without_tax_ytd_all,
tmago_sales_qty_ton,
tmago_sales_qty_ton_mtd,
0 tmago_sales_qty_ton_ytd,
tmago_sales_qty_box,
tmago_sales_qty_box_mtd,
0 tmago_sales_qty_box_ytd,
tmago_sales_amt_before,
tmago_sales_amt_before_mtd,
0 tmago_sales_amt_before_ytd,
tmago_sales_amt_after,
tmago_sales_amt_after_mtd,
0 tmago_sales_amt_after_ytd,
tmago_amt_bf_without_tax,
tmago_amt_bf_without_tax_mtd,
0 tmago_amt_bf_without_tax_ytd,
tmago_amt_af_without_tax,
tmago_amt_af_without_tax_mtd,
0 tmago_amt_af_without_tax_ytd,
plan_amt_before,
plan_amt_before_mtd,
0 plan_amt_before_ytd,
plan_amt_after,
plan_amt_after_mtd,
0 plan_amt_after_ytd,
task_amt_before,
task_amt_before_mtd,
0 task_amt_before_ytd,
0 task_amt_before_ytd_all,
task_amt_after,
task_amt_after_mtd,
0 task_amt_after_ytd,
0 task_amt_after_ytd_all,
budget_amt_before,
budget_amt_before_mtd,
0 budget_amt_before_ytd,
0 budget_amt_before_ytd_all,
budget_amt_after,
budget_amt_after_mtd,
0 budget_amt_after_ytd,
0 budget_amt_after_ytd_all,
yago_plan_amt_before,
yago_plan_amt_before_mtd,
0 yago_plan_amt_before_ytd,
yago_plan_amt_after,
yago_plan_amt_after_mtd,
0 yago_plan_amt_after_ytd,
yago_task_amt_before,
yago_task_amt_before_mtd,
0 yago_task_amt_before_ytd,
0 yago_task_amt_before_ytd_all,
yago_task_amt_after,
yago_task_amt_after_mtd,
0 yago_task_amt_after_ytd,
0 yago_task_amt_after_ytd_all,
yago_budget_amt_before,
yago_budget_amt_before_mtd,
0 yago_budget_amt_before_ytd,
0 yago_budget_amt_before_ytd_all,
yago_budget_amt_after,
yago_budget_amt_after_mtd,
0 yago_budget_amt_after_ytd,
0 yago_budget_amt_after_ytd_all,
mago_plan_amt_before,
mago_plan_amt_before_mtd,
0 mago_plan_amt_before_ytd,
mago_plan_amt_after,
mago_plan_amt_after_mtd,
0 mago_plan_amt_after_ytd,
mago_task_amt_before,
mago_task_amt_before_mtd,
0 mago_task_amt_before_ytd,
0 mago_task_amt_before_ytd_all,
mago_task_amt_after,
mago_task_amt_after_mtd,
0 mago_task_amt_after_ytd,
0 mago_task_amt_after_ytd_all,
mago_budget_amt_before,
mago_budget_amt_before_mtd,
0 mago_budget_amt_before_ytd,
0 mago_budget_amt_before_ytd_all,
mago_budget_amt_after,
mago_budget_amt_after_mtd,
0 mago_budget_amt_after_ytd,
0 mago_budget_amt_after_ytd_all,
tmago_plan_amt_before,
tmago_plan_amt_before_mtd,
0 tmago_plan_amt_before_ytd,
tmago_plan_amt_after,
tmago_plan_amt_after_mtd,
0 tmago_plan_amt_after_ytd,
tmago_task_amt_before,
tmago_task_amt_before_mtd,
0 tmago_task_amt_before_ytd,
0 tmago_task_amt_before_ytd_all,
tmago_task_amt_after,
tmago_task_amt_after_mtd,
0 tmago_task_amt_after_ytd,
0 tmago_task_amt_after_ytd_all,
tmago_budget_amt_before,
tmago_budget_amt_before_mtd,
0 tmago_budget_amt_before_ytd,
0 tmago_budget_amt_before_ytd_all,
tmago_budget_amt_after,
tmago_budget_amt_after_mtd,
0 tmago_budget_amt_after_ytd,
0 tmago_budget_amt_after_ytd_all,
1 complete_percent_target,
substr(sales_dt_wid,1,4) as sales_year,
substr(sales_dt_wid,1,6) as date_
from
(select
t.sales_dt_wid,
t.bg_wid,
t.platform_name,
t.sale_area_name,
t.dealer_wid,
t.erp_id,
t.pro_id,
t.pro_categ_name,
t.pro_brand_name,
t.pro_grade,
t.site_wid,
sum(case when type= 'D' then sales_qty_ton else 0 end) sales_qty_ton,
sum(case when type= 'D' then sales_qty_box else 0 end) sales_qty_box,
sum(case when type= 'D' then sales_amt_before else 0 end) sales_amt_before,
sum(case when type= 'D' then sales_amt_after else 0 end) sales_amt_after,
sum(case when type= 'D' then amt_bf_without_tax else 0 end) amt_bf_without_tax,
sum(case when type= 'D' then amt_af_without_tax else 0 end) amt_af_without_tax,
sum(case when type= 'D' then plan_qty_ton else 0 end) plan_qty_ton,
sum(case when type= 'D' then plan_qty_box else 0 end) plan_qty_box,
sum(case when type= 'D' then plan_amt_bf_without_tax else 0 end) plan_amt_bf_without_tax,
sum(case when type= 'D' then plan_amt_af_without_tax else 0 end) plan_amt_af_without_tax,
sum(case when type= 'D' then task_qty_ton else 0 end) task_qty_ton,
sum(case when type= 'D' then task_qty_box else 0 end) task_qty_box,
sum(case when type= 'D' then task_amt_bf_without_tax else 0 end) task_amt_bf_without_tax,
sum(case when type= 'D' then task_amt_af_without_tax else 0 end) task_amt_af_without_tax,
sum(case when type= 'D' then budget_qty_ton else 0 end) budget_qty_ton,
sum(case when type= 'D' then budget_qty_box else 0 end) budget_qty_box,
sum(case when type= 'D' then budget_amt_bf_without_tax else 0 end) budget_amt_bf_without_tax,
sum(case when type= 'D' then budget_amt_af_without_tax else 0 end) budget_amt_af_without_tax,
sum(case when type= 'D' then plan_amt_before else 0 end) plan_amt_before,
sum(case when type= 'D' then plan_amt_after else 0 end) plan_amt_after,
sum(case when type= 'D' then task_amt_before else 0 end) task_amt_before,
sum(case when type= 'D' then task_amt_after else 0 end) task_amt_after,
sum(case when type= 'D' then budget_amt_before else 0 end) budget_amt_before,
sum(case when type= 'D' then budget_amt_after else 0 end) budget_amt_after,
sum(case when type= 'D' then mago_sales_qty_ton else 0 end) mago_sales_qty_ton,
sum(case when type= 'D' then mago_sales_qty_box else 0 end) mago_sales_qty_box,
sum(case when type= 'D' then mago_amt_before else 0 end) mago_amt_before,
sum(case when type= 'D' then mago_amt_bf_without_tax else 0 end) mago_amt_bf_without_tax,
sum(case when type= 'D' then mago_amt_after else 0 end) mago_amt_after,
sum(case when type= 'D' then mago_amt_af_without_tax else 0 end) mago_amt_af_without_tax,
sum(case when type= 'D' then mago_plan_amt_before else 0 end) mago_plan_amt_before,
sum(case when type= 'D' then mago_plan_amt_after else 0 end) mago_plan_amt_after,
sum(case when type= 'D' then mago_task_amt_before else 0 end) mago_task_amt_before,
sum(case when type= 'D' then mago_task_amt_after else 0 end) mago_task_amt_after,
sum(case when type= 'D' then mago_budget_amt_before else 0 end) mago_budget_amt_before,
sum(case when type= 'D' then mago_budget_amt_after else 0 end) mago_budget_amt_after,
sum(case when type= 'D' then tmago_sales_qty_ton else 0 end) tmago_sales_qty_ton,
sum(case when type= 'D' then tmago_sales_qty_box else 0 end) tmago_sales_qty_box,
sum(case when type= 'D' then tmago_sales_amt_before else 0 end) tmago_sales_amt_before,
sum(case when type= 'D' then tmago_sales_amt_after else 0 end) tmago_sales_amt_after,
sum(case when type= 'D' then tmago_amt_bf_without_tax else 0 end) tmago_amt_bf_without_tax,
sum(case when type= 'D' then tmago_amt_af_without_tax else 0 end) tmago_amt_af_without_tax,
sum(case when type= 'D' then tmago_plan_amt_before else 0 end) tmago_plan_amt_before,
sum(case when type= 'D' then tmago_plan_amt_after else 0 end) tmago_plan_amt_after,
sum(case when type= 'D' then tmago_task_amt_before else 0 end) tmago_task_amt_before,
sum(case when type= 'D' then tmago_task_amt_after else 0 end) tmago_task_amt_after,
sum(case when type= 'D' then tmago_budget_amt_before else 0 end) tmago_budget_amt_before,
sum(case when type= 'D' then tmago_budget_amt_after else 0 end) tmago_budget_amt_after,
sum(case when type= 'D' then yago_sales_qty_ton else 0 end) yago_sales_qty_ton,
sum(case when type= 'D' then yago_sales_qty_box else 0 end) yago_sales_qty_box,
sum(case when type= 'D' then yago_amt_before else 0 end) yago_amt_before,
sum(case when type= 'D' then yago_amt_bf_without_tax else 0 end) yago_amt_bf_without_tax,
sum(case when type= 'D' then yago_amt_after else 0 end) yago_amt_after,
sum(case when type= 'D' then yago_amt_af_without_tax else 0 end) yago_amt_af_without_tax,
sum(case when type= 'D' then yago_plan_qty_ton else 0 end) yago_plan_qty_ton,
sum(case when type= 'D' then yago_plan_qty_box else 0 end) yago_plan_qty_box,
sum(case when type= 'D' then yago_plan_amt_bf_no_tax else 0 end) yago_plan_amt_bf_no_tax,
sum(case when type= 'D' then yago_plan_amt_af_no_tax else 0 end) yago_plan_amt_af_no_tax,
sum(case when type= 'D' then yago_task_qty_ton else 0 end) yago_task_qty_ton,
sum(case when type= 'D' then yago_task_qty_box else 0 end) yago_task_qty_box,
sum(case when type= 'D' then yago_task_amt_bf_no_tax else 0 end) yago_task_amt_bf_no_tax,
sum(case when type= 'D' then yago_task_amt_af_no_tax else 0 end) yago_task_amt_af_no_tax,
sum(case when type= 'D' then yago_budget_qty_ton else 0 end) yago_budget_qty_ton,
sum(case when type= 'D' then yago_budget_qty_box else 0 end) yago_budget_qty_box,
sum(case when type= 'D' then yago_budget_amt_bf_without_tax else 0 end) yago_budget_amt_bf_without_tax,
sum(case when type= 'D' then yago_budget_amt_af_without_tax else 0 end) yago_budget_amt_af_without_tax,
sum(case when type= 'D' then yago_plan_amt_before else 0 end) yago_plan_amt_before,
sum(case when type= 'D' then yago_plan_amt_after else 0 end) yago_plan_amt_after,
sum(case when type= 'D' then yago_task_amt_before else 0 end) yago_task_amt_before,
sum(case when type= 'D' then yago_task_amt_after else 0 end) yago_task_amt_after,
sum(case when type= 'D' then yago_budget_amt_before else 0 end) yago_budget_amt_before,
sum(case when type= 'D' then yago_budget_amt_after else 0 end) yago_budget_amt_after,
sum(case when type= 'MTD' then sales_qty_ton else 0 end) sales_qty_ton_mtd,
sum(case when type= 'MTD' then sales_qty_box else 0 end) sales_qty_box_mtd,
sum(case when type= 'MTD' then sales_amt_before else 0 end) sales_amt_before_mtd,
sum(case when type= 'MTD' then sales_amt_after else 0 end) sales_amt_after_mtd,
sum(case when type= 'MTD' then amt_bf_without_tax else 0 end) amt_bf_without_tax_mtd,
sum(case when type= 'MTD' then amt_af_without_tax else 0 end) amt_af_without_tax_mtd,
sum(case when type= 'MTD' then plan_qty_ton else 0 end) plan_qty_ton_mtd,
sum(case when type= 'MTD' then plan_qty_box else 0 end) plan_qty_box_mtd,
sum(case when type= 'MTD' then plan_amt_bf_without_tax else 0 end) plan_amt_bf_without_tax_mtd,
sum(case when type= 'MTD' then plan_amt_af_without_tax else 0 end) plan_amt_af_without_tax_mtd,
sum(case when type= 'MTD' then task_qty_ton else 0 end) task_qty_ton_mtd,
sum(case when type= 'MTD' then task_qty_box else 0 end) task_qty_box_mtd,
sum(case when type= 'MTD' then task_amt_bf_without_tax else 0 end) task_amt_bf_without_tax_mtd,
sum(case when type= 'MTD' then task_amt_af_without_tax else 0 end) task_amt_af_without_tax_mtd,
sum(case when type= 'MTD' then budget_qty_ton else 0 end) budget_qty_ton_mtd,
sum(case when type= 'MTD' then budget_qty_box else 0 end) budget_qty_box_mtd,
sum(case when type= 'MTD' then budget_amt_bf_without_tax else 0 end) budget_amt_bf_without_tax_mtd,
sum(case when type= 'MTD' then budget_amt_af_without_tax else 0 end) budget_amt_af_without_tax_mtd,
sum(case when type= 'MTD' then plan_amt_before else 0 end) plan_amt_before_mtd,
sum(case when type= 'MTD' then plan_amt_after else 0 end) plan_amt_after_mtd,
sum(case when type= 'MTD' then task_amt_before else 0 end) task_amt_before_mtd,
sum(case when type= 'MTD' then task_amt_after else 0 end) task_amt_after_mtd,
sum(case when type= 'MTD' then budget_amt_before else 0 end) budget_amt_before_mtd,
sum(case when type= 'MTD' then budget_amt_after else 0 end) budget_amt_after_mtd,
sum(case when type= 'MTD' then mago_sales_qty_ton else 0 end) mago_sales_qty_ton_mtd,
sum(case when type= 'MTD' then mago_sales_qty_box else 0 end) mago_sales_qty_box_mtd,
sum(case when type= 'MTD' then mago_amt_before else 0 end) mago_amt_before_mtd,
sum(case when type= 'MTD' then mago_amt_bf_without_tax else 0 end) mago_amt_bf_without_tax_mtd,
sum(case when type= 'MTD' then mago_amt_after else 0 end) mago_amt_after_mtd,
sum(case when type= 'MTD' then mago_amt_af_without_tax else 0 end) mago_amt_af_without_tax_mtd,
sum(case when type= 'MTD' then mago_plan_amt_before else 0 end) mago_plan_amt_before_mtd,
sum(case when type= 'MTD' then mago_plan_amt_after else 0 end) mago_plan_amt_after_mtd,
sum(case when type= 'MTD' then mago_task_amt_before else 0 end) mago_task_amt_before_mtd,
sum(case when type= 'MTD' then mago_task_amt_after else 0 end) mago_task_amt_after_mtd,
sum(case when type= 'MTD' then mago_budget_amt_before else 0 end) mago_budget_amt_before_mtd,
sum(case when type= 'MTD' then mago_budget_amt_after else 0 end) mago_budget_amt_after_mtd,
sum(case when type= 'MTD' then tmago_sales_qty_ton else 0 end) tmago_sales_qty_ton_mtd,
sum(case when type= 'MTD' then tmago_sales_qty_box else 0 end) tmago_sales_qty_box_mtd,
sum(case when type= 'MTD' then tmago_sales_amt_before else 0 end) tmago_sales_amt_before_mtd,
sum(case when type= 'MTD' then tmago_sales_amt_after else 0 end) tmago_sales_amt_after_mtd,
sum(case when type= 'MTD' then tmago_amt_bf_without_tax else 0 end) tmago_amt_bf_without_tax_mtd,
sum(case when type= 'MTD' then tmago_amt_af_without_tax else 0 end) tmago_amt_af_without_tax_mtd,
sum(case when type= 'MTD' then tmago_plan_amt_before else 0 end) tmago_plan_amt_before_mtd,
sum(case when type= 'MTD' then tmago_plan_amt_after else 0 end) tmago_plan_amt_after_mtd,
sum(case when type= 'MTD' then tmago_task_amt_before else 0 end) tmago_task_amt_before_mtd,
sum(case when type= 'MTD' then tmago_task_amt_after else 0 end) tmago_task_amt_after_mtd,
sum(case when type= 'MTD' then tmago_budget_amt_before else 0 end) tmago_budget_amt_before_mtd,
sum(case when type= 'MTD' then tmago_budget_amt_after else 0 end) tmago_budget_amt_after_mtd,
sum(case when type= 'MTD' then yago_sales_qty_ton else 0 end) yago_sales_qty_ton_mtd,
sum(case when type= 'MTD' then yago_sales_qty_box else 0 end) yago_sales_qty_box_mtd,
sum(case when type= 'MTD' then yago_amt_before else 0 end) yago_amt_before_mtd,
sum(case when type= 'MTD' then yago_amt_bf_without_tax else 0 end) yago_amt_bf_without_tax_mtd,
sum(case when type= 'MTD' then yago_amt_after else 0 end) yago_amt_after_mtd,
sum(case when type= 'MTD' then yago_amt_af_without_tax else 0 end) yago_amt_af_without_tax_mtd,
sum(case when type= 'MTD' then yago_plan_qty_ton else 0 end) yago_plan_qty_ton_mtd,
sum(case when type= 'MTD' then yago_plan_qty_box else 0 end) yago_plan_qty_box_mtd,
sum(case when type= 'MTD' then yago_plan_amt_bf_no_tax else 0 end) yago_plan_amt_bf_no_tax_mtd,
sum(case when type= 'MTD' then yago_plan_amt_af_no_tax else 0 end) yago_plan_amt_af_no_tax_mtd,
sum(case when type= 'MTD' then yago_task_qty_ton else 0 end) yago_task_qty_ton_mtd,
sum(case when type= 'MTD' then yago_task_qty_box else 0 end) yago_task_qty_box_mtd,
sum(case when type= 'MTD' then yago_task_amt_bf_no_tax else 0 end) yago_task_amt_bf_no_tax_mtd,
sum(case when type= 'MTD' then yago_task_amt_af_no_tax else 0 end) yago_task_amt_af_no_tax_mtd,
sum(case when type= 'MTD' then yago_budget_qty_ton else 0 end) yago_budget_qty_ton_mtd,
sum(case when type= 'MTD' then yago_budget_qty_box else 0 end) yago_budget_qty_box_mtd,
sum(case when type= 'MTD' then yago_budget_amt_bf_without_tax else 0 end) yago_budget_amt_bf_without_tax_mtd,
sum(case when type= 'MTD' then yago_budget_amt_af_without_tax else 0 end) yago_budget_amt_af_without_tax_mtd,
sum(case when type= 'MTD' then yago_plan_amt_before else 0 end) yago_plan_amt_before_mtd,
sum(case when type= 'MTD' then yago_plan_amt_after else 0 end) yago_plan_amt_after_mtd,
sum(case when type= 'MTD' then yago_task_amt_before else 0 end) yago_task_amt_before_mtd,
sum(case when type= 'MTD' then yago_task_amt_after else 0 end) yago_task_amt_after_mtd,
sum(case when type= 'MTD' then yago_budget_amt_before else 0 end) yago_budget_amt_before_mtd,
sum(case when type= 'MTD' then yago_budget_amt_after else 0 end) yago_budget_amt_after_mtd
from 
(select
sales_dt_wid,
bg_wid,
platform_name,
sale_area_name,
dealer_wid,
erp_id,
pro_id,
pro_categ_name,
pro_brand_name,
pro_grade,
'D' as type,
site_wid,
sales_qty_ton,
sales_qty_box,
sales_amt_before,
sales_amt_after,
amt_bf_without_tax,
amt_af_without_tax,
plan_qty_ton,
plan_qty_box,
plan_amt_bf_without_tax,
plan_amt_af_without_tax,
task_qty_ton,
task_qty_box,
task_amt_bf_without_tax,
task_amt_af_without_tax,
budget_qty_ton,
budget_qty_box,
budget_amt_bf_without_tax,
budget_amt_af_without_tax,
plan_amt_before,
plan_amt_after,
task_amt_before,
task_amt_after,
budget_amt_before,
budget_amt_after,
mago_sales_qty_ton,
mago_sales_qty_box,
mago_amt_before,
mago_amt_bf_without_tax,
mago_amt_after,
mago_amt_af_without_tax,
mago_plan_amt_before,
mago_plan_amt_after,
mago_task_amt_before,
mago_task_amt_after,
mago_budget_amt_before,
mago_budget_amt_after,
tmago_sales_qty_ton,
tmago_sales_qty_box,
tmago_sales_amt_before,
tmago_sales_amt_after,
tmago_amt_bf_without_tax,
tmago_amt_af_without_tax,
tmago_plan_amt_before,
tmago_plan_amt_after,
tmago_task_amt_before,
tmago_task_amt_after,
tmago_budget_amt_before,
tmago_budget_amt_after,
yago_sales_qty_ton,
yago_sales_qty_box,
yago_amt_before,
yago_amt_bf_without_tax,
yago_amt_after,
yago_amt_af_without_tax,
yago_plan_qty_ton,
yago_plan_qty_box,
yago_plan_amt_bf_no_tax,
yago_plan_amt_af_no_tax,
yago_task_qty_ton,
yago_task_qty_box,
yago_task_amt_bf_no_tax,
yago_task_amt_af_no_tax,
yago_budget_qty_ton,
yago_budget_qty_box,
yago_budget_amt_bf_without_tax,
yago_budget_amt_af_without_tax,
yago_plan_amt_before,
yago_plan_amt_after,
yago_task_amt_before,
yago_task_amt_after,
yago_budget_amt_before,
yago_budget_amt_after
from bigdata_dm.pj_ec_sales_gmv_ago
where date_ >='201801'
union all
select
day_id,
bg_wid,
platform_name,
sale_area_name,
dealer_wid,
erp_id,
pro_id,
pro_categ_name,
pro_brand_name,
pro_grade,
`type`,
site_wid,
sales_qty_ton,
sales_qty_box,
sales_amt_before,
sales_amt_after,
amt_bf_without_tax,
amt_af_without_tax,
plan_qty_ton,
plan_qty_box,
plan_amt_bf_without_tax,
plan_amt_af_without_tax,
task_qty_ton,
task_qty_box,
task_amt_bf_without_tax,
task_amt_af_without_tax,
budget_qty_ton,
budget_qty_box,
budget_amt_bf_without_tax,
budget_amt_af_without_tax,
plan_amt_before,
plan_amt_after,
task_amt_before,
task_amt_after,
budget_amt_before,
budget_amt_after,
mago_sales_qty_ton,
mago_sales_qty_box,
mago_amt_before,
mago_amt_bf_without_tax,
mago_amt_after,
mago_amt_af_without_tax,
mago_plan_amt_before,
mago_plan_amt_after,
mago_task_amt_before,
mago_task_amt_after,
mago_budget_amt_before,
mago_budget_amt_after,
tmago_sales_qty_ton,
tmago_sales_qty_box,
tmago_sales_amt_before,
tmago_sales_amt_after,
tmago_amt_bf_without_tax,
tmago_amt_af_without_tax,
tmago_plan_amt_before,
tmago_plan_amt_after,
tmago_task_amt_before,
tmago_task_amt_after,
tmago_budget_amt_before,
tmago_budget_amt_after,
yago_sales_qty_ton,
yago_sales_qty_box,
yago_amt_before,
yago_amt_bf_without_tax,
yago_amt_after,
yago_amt_af_without_tax,
yago_plan_qty_ton,
yago_plan_qty_box,
yago_plan_amt_bf_no_tax,
yago_plan_amt_af_no_tax,
yago_task_qty_ton,
yago_task_qty_box,
yago_task_amt_bf_no_tax,
yago_task_amt_af_no_tax,
yago_budget_qty_ton,
yago_budget_qty_box,
yago_budget_amt_bf_without_tax,
yago_budget_amt_af_without_tax,
yago_plan_amt_before,
yago_plan_amt_after,
yago_task_amt_before,
yago_task_amt_after,
yago_budget_amt_before,
yago_budget_amt_after
from bigdata_dm.pj_ec_sales_gmv_mtd_init
where date_ >='201801' and date_ <=regexp_replace(substr(date_sub(current_date,1),1,7),'-','')
) t
group by
t.sales_dt_wid,
t.bg_wid,
t.platform_name,
t.sale_area_name,
t.dealer_wid,
t.erp_id,
t.pro_id,
t.pro_categ_name,
t.pro_brand_name,
t.pro_grade,
t.site_wid) t1;

--由于麒麟缘故，pro_id和erp_id 位置对调
insert overwrite table bigdata_dm.pj_ec_sales_gmv partition(date_)
select
sales_dt_wid,
bg_wid,
platform_name,
sale_area_name,
dealer_wid,
pro_id,
erp_id,
pro_categ_name,
pro_brand_name,
pro_grade,
site_wid,
w_insert_dt,
price_before,
price_after,
sales_qty_ton,
sales_qty_ton_mtd,
sales_qty_ton_ytd,
sales_qty_box,
sales_qty_box_mtd,
sales_qty_box_ytd,
sales_amt_before,
sales_amt_before_mtd,
sales_amt_before_ytd,
sales_amt_after,
sales_amt_after_mtd,
sales_amt_after_ytd,
amt_bf_without_tax,
amt_bf_without_tax_mtd,
amt_bf_without_tax_ytd,
amt_af_without_tax,
amt_af_without_tax_mtd,
amt_af_without_tax_ytd,
plan_qty_ton,
plan_qty_ton_mtd,
plan_qty_ton_ytd,
plan_qty_box,
plan_qty_box_mtd,
plan_qty_box_ytd,
plan_amt_bf_without_tax,
plan_amt_bf_without_tax_mtd,
plan_amt_bf_without_tax_ytd,
plan_amt_af_without_tax,
plan_amt_af_without_tax_mtd,
plan_amt_af_without_tax_ytd,
task_qty_ton,
task_qty_ton_mtd,
task_qty_ton_ytd,
task_qty_ton_ytd_all,
task_qty_box,
task_qty_box_mtd,
task_qty_box_ytd,
task_qty_box_ytd_all,
task_amt_bf_without_tax,
task_amt_bf_without_tax_mtd,
task_amt_bf_without_tax_ytd,
task_amt_bf_without_tax_ytd_all,
task_amt_af_without_tax,
task_amt_af_without_tax_mtd,
task_amt_af_without_tax_ytd,
task_amt_af_without_tax_ytd_all,
budget_qty_ton,
budget_qty_ton_mtd,
budget_qty_ton_ytd,
budget_qty_ton_ytd_all,
budget_qty_box,
budget_qty_box_mtd,
budget_qty_box_ytd,
budget_qty_box_ytd_all,
budget_amt_bf_without_tax,
budget_amt_bf_without_tax_mtd,
budget_amt_bf_without_tax_ytd,
budget_amt_bf_without_tax_ytd_all,
budget_amt_af_without_tax,
budget_amt_af_without_tax_mtd,
budget_amt_af_without_tax_ytd,
budget_amt_af_without_tax_ytd_all,
mago_sales_qty_ton,
mago_sales_qty_ton_mtd,
mago_sales_qty_ton_ytd,
mago_sales_qty_box,
mago_sales_qty_box_mtd,
mago_sales_qty_box_ytd,
mago_amt_before,
mago_amt_before_mtd,
mago_amt_before_ytd,
mago_amt_bf_without_tax,
mago_amt_bf_without_tax_mtd,
mago_amt_bf_without_tax_ytd,
mago_amt_after,
mago_amt_after_mtd,
mago_amt_after_ytd,
mago_amt_af_without_tax,
mago_amt_af_without_tax_mtd,
mago_amt_af_without_tax_ytd,
yago_sales_qty_ton,
yago_sales_qty_ton_mtd,
yago_sales_qty_ton_ytd,
yago_sales_qty_box,
yago_sales_qty_box_mtd,
yago_sales_qty_box_ytd,
yago_amt_before,
yago_amt_before_mtd,
yago_amt_before_ytd,
yago_amt_bf_without_tax,
yago_amt_bf_without_tax_mtd,
yago_amt_bf_without_tax_ytd,
yago_amt_after,
yago_amt_after_mtd,
yago_amt_after_ytd,
yago_amt_af_without_tax,
yago_amt_af_without_tax_mtd,
yago_amt_af_without_tax_ytd,
yago_plan_qty_ton,
yago_plan_qty_ton_mtd,
yago_plan_qty_ton_ytd,
yago_plan_qty_box,
yago_plan_qty_box_mtd,
yago_plan_qty_box_ytd,
yago_plan_amt_bf_no_tax,
yago_plan_amt_bf_no_tax_mtd,
yago_plan_amt_bf_no_tax_ytd,
yago_plan_amt_af_no_tax,
yago_plan_amt_af_no_tax_mtd,
yago_plan_amt_af_no_tax_ytd,
yago_task_qty_ton,
yago_task_qty_ton_mtd,
yago_task_qty_ton_ytd,
yago_task_qty_ton_ytd_all,
yago_task_qty_box,
yago_task_qty_box_mtd,
yago_task_qty_box_ytd,
yago_task_qty_box_ytd_all,
yago_task_amt_bf_no_tax,
yago_task_amt_bf_no_tax_mtd,
yago_task_amt_bf_no_tax_ytd,
yago_task_amt_bf_no_tax_ytd_all,
yago_task_amt_af_no_tax,
yago_task_amt_af_no_tax_mtd,
yago_task_amt_af_no_tax_ytd,
yago_task_amt_af_no_tax_ytd_all,
yago_budget_qty_ton,
yago_budget_qty_ton_mtd,
yago_budget_qty_ton_ytd,
yago_budget_qty_ton_ytd_all,
yago_budget_qty_box,
yago_budget_qty_box_mtd,
yago_budget_qty_box_ytd,
yago_budget_qty_box_ytd_all,
yago_budget_amt_bf_without_tax,
yago_budget_amt_bf_without_tax_mtd,
yago_budget_amt_bf_without_tax_ytd,
yago_budget_amt_bf_without_tax_ytd_all,
yago_budget_amt_af_without_tax,
yago_budget_amt_af_without_tax_mtd,
yago_budget_amt_af_without_tax_ytd,
yago_budget_amt_af_without_tax_ytd_all,
tmago_sales_qty_ton,
tmago_sales_qty_ton_mtd,
tmago_sales_qty_ton_ytd,
tmago_sales_qty_box,
tmago_sales_qty_box_mtd,
tmago_sales_qty_box_ytd,
tmago_sales_amt_before,
tmago_sales_amt_before_mtd,
tmago_sales_amt_before_ytd,
tmago_sales_amt_after,
tmago_sales_amt_after_mtd,
tmago_sales_amt_after_ytd,
tmago_amt_bf_without_tax,
tmago_amt_bf_without_tax_mtd,
tmago_amt_bf_without_tax_ytd,
tmago_amt_af_without_tax,
tmago_amt_af_without_tax_mtd,
tmago_amt_af_without_tax_ytd,
plan_amt_before,
plan_amt_before_mtd,
plan_amt_before_ytd,
plan_amt_after,
plan_amt_after_mtd,
plan_amt_after_ytd,
task_amt_before,
task_amt_before_mtd,
task_amt_before_ytd,
task_amt_before_ytd_all,
task_amt_after,
task_amt_after_mtd,
task_amt_after_ytd,
task_amt_after_ytd_all,
budget_amt_before,
budget_amt_before_mtd,
budget_amt_before_ytd,
budget_amt_before_ytd_all,
budget_amt_after,
budget_amt_after_mtd,
budget_amt_after_ytd,
budget_amt_after_ytd_all,
yago_plan_amt_before,
yago_plan_amt_before_mtd,
yago_plan_amt_before_ytd,
yago_plan_amt_after,
yago_plan_amt_after_mtd,
yago_plan_amt_after_ytd,
yago_task_amt_before,
yago_task_amt_before_mtd,
yago_task_amt_before_ytd,
yago_task_amt_before_ytd_all,
yago_task_amt_after,
yago_task_amt_after_mtd,
yago_task_amt_after_ytd,
yago_task_amt_after_ytd_all,
yago_budget_amt_before,
yago_budget_amt_before_mtd,
yago_budget_amt_before_ytd,
yago_budget_amt_before_ytd_all,
yago_budget_amt_after,
yago_budget_amt_after_mtd,
yago_budget_amt_after_ytd,
yago_budget_amt_after_ytd_all,
mago_plan_amt_before,
mago_plan_amt_before_mtd,
mago_plan_amt_before_ytd,
mago_plan_amt_after,
mago_plan_amt_after_mtd,
mago_plan_amt_after_ytd,
mago_task_amt_before,
mago_task_amt_before_mtd,
mago_task_amt_before_ytd,
mago_task_amt_before_ytd_all,
mago_task_amt_after,
mago_task_amt_after_mtd,
mago_task_amt_after_ytd,
mago_task_amt_after_ytd_all,
mago_budget_amt_before,
mago_budget_amt_before_mtd,
mago_budget_amt_before_ytd,
mago_budget_amt_before_ytd_all,
mago_budget_amt_after,
mago_budget_amt_after_mtd,
mago_budget_amt_after_ytd,
mago_budget_amt_after_ytd_all,
tmago_plan_amt_before,
tmago_plan_amt_before_mtd,
tmago_plan_amt_before_ytd,
tmago_plan_amt_after,
tmago_plan_amt_after_mtd,
tmago_plan_amt_after_ytd,
tmago_task_amt_before,
tmago_task_amt_before_mtd,
tmago_task_amt_before_ytd,
tmago_task_amt_before_ytd_all,
tmago_task_amt_after,
tmago_task_amt_after_mtd,
tmago_task_amt_after_ytd,
tmago_task_amt_after_ytd_all,
tmago_budget_amt_before,
tmago_budget_amt_before_mtd,
tmago_budget_amt_before_ytd,
tmago_budget_amt_before_ytd_all,
tmago_budget_amt_after,
tmago_budget_amt_after_mtd,
tmago_budget_amt_after_ytd,
tmago_budget_amt_after_ytd_all,
complete_percent_target,
sales_year,
date_
from bigdata_dm.pj_ec_sales_gmv_mtd_tmp;

--把新增的sku_id插入到产品表，防止麒麟查不到数据
insert overwrite table bigdata_dw.w_ec_product_d partition(dual_='2')
select 
t2.erp_id as row_wid,
'-1' as seq_num,
'-1' as categ_name,
t2.erp_id as sku_id,
'其他' as erp_id,
'其他' as erp_name,
'其他' as erp_unit,
'其他' as platform_name,
'其他' as platform_unit,
'其他' as final_name,
'其他' as pro_categ_cd,
'其他' as pro_categ_name,
'其他' as pro_brand_cd,
'其他' as pro_brand_name,
'其他' as pro_grade,
'1' as proc_coef,
'0' as if_comb_flag,
'1' as skuid_seq,
null as attr1,
null as attr2,
null as attr3,
null as attr4,
null as attr5,
null as attr6,
null as attr7,
null as attr8,
null as attr9,
null as attr10,
from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss') as w_insert_dt
from (select  distinct t.erp_id as erp_id  from bigdata_dm.pj_ec_sales_gmv t
left outer join bigdata_dw.w_ec_product_d t1
on t.erp_id=t1.row_wid and t1.dual_ in ('0','1')
where t1.row_wid is null) t2;


