-------------------------------------------------------------------------------
-- (c) copyright capgemini
-- file name:               PJ_EC_SALES_SI_TMP_INIT.sql
-- source table:            
-- target table:            
-- project:
-- note:
-- purpose:                 计算MTD,YTD,同期值，上月值等
--=============================================================================
-- creation date:       2019-3-7
-- origin author:       capgemini
--no
-- version: %1.0%
--
-- modification history
-- --------------------
-- date         byperson        description
-- ----------   --------------  -----------------------------------------------
-- 2019-3-21 capgemini       
-------------------------------------------------------------------------------
set parquet.compression=GZIP;
set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.max.dynamic.partitions.pernode=10000;
insert overwrite table bigdata_dm.pj_ec_sales_si_mtd_tmp partition(date_)
select
t.sales_dt_wid,
t.bg_wid,
nvl(t3.platform_name,'-1') as platform_name,
nvl(t3.sale_area_name,'-1') as sale_area_name,
t.dealer_wid,
nvl(t1.erp_id,'-1') as erp_id,
'-1' as pro_id,
nvl(t1.pro_categ_name,'-1') as pro_categ_name,
nvl(t1.pro_brand_name,'-1') as pro_brand_name,
case when t1.pro_grade='无' or t1.pro_grade='未定义'  or t1.pro_grade ='缺省'  or  t1.pro_grade ='-1' then '空' else t1.pro_grade end pro_grade,
t.site_wid,
from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss')  as w_insert_dt,
t.price_before,
t.price_after,
t.sales_qty_ton,
t.sales_qty_ton_mtd,
0 sales_qty_ton_ytd,
t.sales_qty_box,
t.sales_qty_box_mtd,
0 sales_qty_box_ytd,
t.sales_amt_before,
t.sales_amt_before_mtd,
0 sales_amt_before_ytd,
t.sales_amt_after,
t.sales_amt_after_mtd,
0 sales_amt_after_ytd,
t.amt_bf_without_tax,
t.amt_bf_without_tax_mtd,
0 amt_bf_without_tax_ytd,
t.amt_af_without_tax,
t.amt_af_without_tax_mtd,
0 amt_af_without_tax_ytd,
t.plan_qty_ton,
t.plan_qty_ton_mtd,
0 plan_qty_ton_ytd,
t.plan_qty_box,
t.plan_qty_box_mtd,
0 plan_qty_box_ytd,
t.plan_amt_bf_without_tax,
t.plan_amt_bf_without_tax_mtd,
0 plan_amt_bf_without_tax_ytd,
t.plan_amt_af_without_tax,
t.plan_amt_af_without_tax_mtd,
0 plan_amt_af_without_tax_ytd,
t.task_qty_ton,
t.task_qty_ton_mtd,
0 task_qty_ton_ytd,
0 task_qty_ton_ytd_all,
t.task_qty_box,
t.task_qty_box_mtd,
0 task_qty_box_ytd,
0 task_qty_box_ytd_all,
t.task_amt_bf_without_tax,
t.task_amt_bf_without_tax_mtd,
0 task_amt_bf_without_tax_ytd,
0 task_amt_bf_without_tax_ytd_all,
t.task_amt_af_without_tax,
t.task_amt_af_without_tax_mtd,
0 task_amt_af_without_tax_ytd,
0 task_amt_af_without_tax_ytd_all,
t.budget_qty_ton,
t.budget_qty_ton_mtd,
0 budget_qty_ton_ytd,
0 budget_qty_ton_ytd_all,
t.budget_qty_box,
t.budget_qty_box_mtd,
0 budget_qty_box_ytd,
0 budget_qty_box_ytd_all,
t.budget_amt_bf_without_tax,
t.budget_amt_bf_without_tax_mtd,
0 budget_amt_bf_without_tax_ytd,
0 budget_amt_bf_without_tax_ytd_all,
t.budget_amt_af_without_tax,
t.budget_amt_af_without_tax_mtd,
0 budget_amt_af_without_tax_ytd,
0 budget_amt_af_without_tax_ytd_all,
t.mago_sales_qty_ton,
t.mago_sales_qty_ton_mtd,
0 mago_sales_qty_ton_ytd,
t.mago_sales_qty_box,
t.mago_sales_qty_box_mtd,
0 mago_sales_qty_box_ytd,
0 mago_amt_before,
0 mago_amt_before_mtd,
0 mago_amt_before_ytd,
0 mago_amt_bf_without_tax,
t.mago_amt_bf_without_tax_mtd,
0 mago_amt_bf_without_tax_ytd,
0 mago_amt_after,
0 mago_amt_after_mtd,
0 mago_amt_after_ytd,
t.mago_amt_af_without_tax,
t.mago_amt_af_without_tax_mtd,
0 mago_amt_af_without_tax_ytd,
t.yago_sales_qty_ton,
t.yago_sales_qty_ton_mtd,
0 yago_sales_qty_ton_ytd,
t.yago_sales_qty_box,
t.yago_sales_qty_box_mtd,
0 yago_sales_qty_box_ytd,
0 yago_amt_before,
0 yago_amt_before_mtd,
0 yago_amt_before_ytd,
t.yago_amt_bf_without_tax,
t.yago_amt_bf_without_tax_mtd,
0 yago_amt_bf_without_tax_ytd,
0 yago_amt_after,
0 yago_amt_after_mtd,
0 yago_amt_after_ytd,
t.yago_amt_af_without_tax,
t.yago_amt_af_without_tax_mtd,
0 yago_amt_af_without_tax_ytd,
t.yago_plan_qty_ton,
t.yago_plan_qty_ton_mtd,
0 yago_plan_qty_ton_ytd,
t.yago_plan_qty_box,
t.yago_plan_qty_box_mtd,
0 yago_plan_qty_box_ytd,
t.yago_plan_amt_bf_no_tax,
t.yago_plan_amt_bf_no_tax_mtd,
0 yago_plan_amt_bf_no_tax_ytd,
t.yago_plan_amt_af_no_tax,
t.yago_plan_amt_af_no_tax_mtd,
0 yago_plan_amt_af_no_tax_ytd,
t.yago_task_qty_ton,
t.yago_task_qty_ton_mtd,
0 yago_task_qty_ton_ytd,
0 yago_task_qty_ton_ytd_all,
t.yago_task_qty_box,
t.yago_task_qty_box_mtd,
0 yago_task_qty_box_ytd,
0 yago_task_qty_box_ytd_all,
t.yago_task_amt_bf_no_tax,
t.yago_task_amt_bf_no_tax_mtd,
0 yago_task_amt_bf_no_tax_ytd,
0 yago_task_amt_bf_no_tax_ytd_all,
t.yago_task_amt_af_no_tax,
t.yago_task_amt_af_no_tax_mtd,
0 yago_task_amt_af_no_tax_ytd,
0 yago_task_amt_af_no_tax_ytd_all,
t.yago_budget_qty_ton,
t.yago_budget_qty_ton_mtd,
0 yago_budget_qty_ton_ytd,
0 yago_budget_qty_ton_ytd_all,
t.yago_budget_qty_box,
t.yago_budget_qty_box_mtd,
0 yago_budget_qty_box_ytd,
0 yago_budget_qty_box_ytd_all,
t.yago_budget_amt_bf_without_tax,
t.yago_budget_amt_bf_without_tax_mtd,
0 yago_budget_amt_bf_without_tax_ytd,
0 yago_budget_amt_bf_without_tax_ytd_all,
t.yago_budget_amt_af_without_tax,
t.yago_budget_amt_af_without_tax_mtd,
0 yago_budget_amt_af_without_tax_ytd,
0 yago_budget_amt_af_without_tax_ytd_all,
0 tmago_sales_qty_ton,
0 tmago_sales_qty_ton_mtd,
0 tmago_sales_qty_ton_ytd,
0 tmago_sales_qty_box,
0 tmago_sales_qty_box_mtd,
0 tmago_sales_qty_box_ytd,
0 tmago_sales_amt_before,
0 tmago_sales_amt_before_mtd,
0 tmago_sales_amt_before_ytd,
0 tmago_sales_amt_after,
0 tmago_sales_amt_after_mtd,
0 tmago_sales_amt_after_ytd,
0 tmago_amt_bf_without_tax,
0 tmago_amt_bf_without_tax_mtd,
0 tmago_amt_bf_without_tax_ytd,
0 tmago_amt_af_without_tax,
0 tmago_amt_af_without_tax_mtd,
0 tmago_amt_af_without_tax_ytd,
0 plan_amt_before,
0 plan_amt_before_mtd,
0 plan_amt_before_ytd,
0 plan_amt_after,
0 plan_amt_after_mtd,
0 plan_amt_after_ytd,
0 task_amt_before,
0 task_amt_before_mtd,
0 task_amt_before_ytd,
0 task_amt_before_ytd_all,
0 task_amt_after,
0 task_amt_after_mtd,
0 task_amt_after_ytd,
0 task_amt_after_ytd_all,
0 budget_amt_before,
0 budget_amt_before_mtd,
0 budget_amt_before_ytd,
0 budget_amt_before_ytd_all,
0 budget_amt_after,
0 budget_amt_after_mtd,
0 budget_amt_after_ytd,
0 budget_amt_after_ytd_all,
0 yago_plan_amt_before,
0 yago_plan_amt_before_mtd,
0 yago_plan_amt_before_ytd,
0 yago_plan_amt_after,
0 yago_plan_amt_after_mtd,
0 yago_plan_amt_after_ytd,
0 yago_task_amt_before,
0 yago_task_amt_before_mtd,
0 yago_task_amt_before_ytd,
0 yago_task_amt_before_ytd_all,
0 yago_task_amt_after,
0 yago_task_amt_after_mtd,
0 yago_task_amt_after_ytd,
0 yago_task_amt_after_ytd_all,
0 yago_budget_amt_before,
0 yago_budget_amt_before_mtd,
0 yago_budget_amt_before_ytd,
0 yago_budget_amt_before_ytd_all,
0 yago_budget_amt_after,
0 yago_budget_amt_after_mtd,
0 yago_budget_amt_after_ytd,
0 yago_budget_amt_after_ytd_all,
0 mago_plan_amt_before,
0 mago_plan_amt_before_mtd,
0 mago_plan_amt_before_ytd,
0 mago_plan_amt_after,
0 mago_plan_amt_after_mtd,
0 mago_plan_amt_after_ytd,
0 mago_task_amt_before,
0 mago_task_amt_before_mtd,
0 mago_task_amt_before_ytd,
0 mago_task_amt_before_ytd_all,
0 mago_task_amt_after,
0 mago_task_amt_after_mtd,
0 mago_task_amt_after_ytd,
0 mago_task_amt_after_ytd_all,
0 mago_budget_amt_before,
0 mago_budget_amt_before_mtd,
0 mago_budget_amt_before_ytd,
0 mago_budget_amt_before_ytd_all,
0 mago_budget_amt_after,
0 mago_budget_amt_after_mtd,
0 mago_budget_amt_after_ytd,
0 mago_budget_amt_after_ytd_all,
0 tmago_plan_amt_before,
0 tmago_plan_amt_before_mtd,
0 tmago_plan_amt_before_ytd,
0 tmago_plan_amt_after,
0 tmago_plan_amt_after_mtd,
0 tmago_plan_amt_after_ytd,
0 tmago_task_amt_before,
0 tmago_task_amt_before_mtd,
0 tmago_task_amt_before_ytd,
0 tmago_task_amt_before_ytd_all,
0 tmago_task_amt_after,
0 tmago_task_amt_after_mtd,
0 tmago_task_amt_after_ytd,
0 tmago_task_amt_after_ytd_all,
0 tmago_budget_amt_before,
0 tmago_budget_amt_before_mtd,
0 tmago_budget_amt_before_ytd,
0 tmago_budget_amt_before_ytd_all,
0 tmago_budget_amt_after,
0 tmago_budget_amt_after_mtd,
0 tmago_budget_amt_after_ytd,
0 tmago_budget_amt_after_ytd_all,
1 complete_percent_target,
t.sales_year,
t.date_
 from bigdata_dm.pj_sales_mtd_tmp t
inner join bigdata_dw.w_ec_product_d1 t1
on t.prod_wid = t1.product_row_wid
left join bigdata_dw.w_area_d t2
on t.area_wid = t2.row_wid
left join (select distinct platform_name,sale_area_name as sale_area_name1, final_name as sale_area_name from bigdata_dw.w_ec_area_d_tmp where platform_type = 'SI') t3 on regexp_extract(regexp_replace(t2.name,'-默认',''),'.*-(.*)',1) = t3.sale_area_name1
where t.date_>=regexp_replace(substr(add_months(date_sub(current_date,1),-1),1,7),'-','') and t.bg_wid=3 and t.prod_wid<>-1 and t1.erp_id  like '2%'

union all

select
d.day_id as sales_dt_wid,
3 bg_wid,
nvl(c.platform_name,'-1') as platform_name,
nvl(c.sale_area_name,'-1') as sale_area_name,
-1 dealer_wid,
'-1'  erp_id,
'-1'  pro_id,
nvl(b.pro_categ_name,'-1') as pro_categ_name,
'-1' pro_brand_name,
'空' pro_grade,
-1 site_wid,
from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss')  as w_insert_dt,
0 price_before,
0 price_after,
0 sales_qty_ton,
0 sales_qty_ton_mtd,
0 sales_qty_ton_ytd,
0 sales_qty_box,
0 sales_qty_box_mtd,
0 sales_qty_box_ytd,
0 sales_amt_before,
0 sales_amt_before_mtd,
0 sales_amt_before_ytd,
0 sales_amt_after,
0 sales_amt_after_mtd,
0 sales_amt_after_ytd,
0 amt_bf_without_tax,
0 amt_bf_without_tax_mtd,
0 amt_bf_without_tax_ytd,
0 amt_af_without_tax,
0 amt_af_without_tax_mtd,
0 amt_af_without_tax_ytd,
0 plan_qty_ton,
0 plan_qty_ton_mtd,
0 plan_qty_ton_ytd,
0 plan_qty_box,
0 plan_qty_box_mtd,
0 plan_qty_box_ytd,
0 plan_amt_bf_without_tax,
0 plan_amt_bf_without_tax_mtd,
0 plan_amt_bf_without_tax_ytd,
0 plan_amt_af_without_tax,
0 plan_amt_af_without_tax_mtd,
0 plan_amt_af_without_tax_ytd,
0 task_qty_ton,
0 task_qty_ton_mtd,
0 task_qty_ton_ytd,
0 task_qty_ton_ytd_all,
0 task_qty_box,
0 task_qty_box_mtd,
0 task_qty_box_ytd,
0 task_qty_box_ytd_all,
0 task_amt_bf_without_tax,
0 task_amt_bf_without_tax_mtd,
0 task_amt_bf_without_tax_ytd,
0 task_amt_bf_without_tax_ytd_all,
0 task_amt_af_without_tax,
0 task_amt_af_without_tax_mtd,
0 task_amt_af_without_tax_ytd,
0 task_amt_af_without_tax_ytd_all,
0 budget_qty_ton,
0 budget_qty_ton_mtd,
0 budget_qty_ton_ytd,
0 budget_qty_ton_ytd_all,
0 budget_qty_box,
0 budget_qty_box_mtd,
0 budget_qty_box_ytd,
0 budget_qty_box_ytd_all,
cast(if(substr(d.day_id,7,2)='01',b.task_amt_before,0) as decimal(38,10)) as budget_amt_bf_without_tax,
cast(b.task_amt_before as decimal(38,10)) as budget_amt_bf_without_tax_mtd,
0 budget_amt_bf_without_tax_ytd,
0 budget_amt_bf_without_tax_ytd_all,
0 budget_amt_af_without_tax,
0 budget_amt_af_without_tax_mtd,
0 budget_amt_af_without_tax_ytd,
0 budget_amt_af_without_tax_ytd_all,
0 mago_sales_qty_ton,
0 mago_sales_qty_ton_mtd,
0 mago_sales_qty_ton_ytd,
0 mago_sales_qty_box,
0 mago_sales_qty_box_mtd,
0 mago_sales_qty_box_ytd,
0 mago_amt_before,
0 mago_amt_before_mtd,
0 mago_amt_before_ytd,
0 mago_amt_bf_without_tax,
0 mago_amt_bf_without_tax_mtd,
0 mago_amt_bf_without_tax_ytd,
0 mago_amt_after,
0 mago_amt_after_mtd,
0 mago_amt_after_ytd,
0 mago_amt_af_without_tax,
0 mago_amt_af_without_tax_mtd,
0 mago_amt_af_without_tax_ytd,
0 yago_sales_qty_ton,
0 yago_sales_qty_ton_mtd,
0 yago_sales_qty_ton_ytd,
0 yago_sales_qty_box,
0 yago_sales_qty_box_mtd,
0 yago_sales_qty_box_ytd,
0 yago_amt_before,
0 yago_amt_before_mtd,
0 yago_amt_before_ytd,
0 yago_amt_bf_without_tax,
0 yago_amt_bf_without_tax_mtd,
0 yago_amt_bf_without_tax_ytd,
0 yago_amt_after,
0 yago_amt_after_mtd,
0 yago_amt_after_ytd,
0 yago_amt_af_without_tax,
0 yago_amt_af_without_tax_mtd,
0 yago_amt_af_without_tax_ytd,
0 yago_plan_qty_ton,
0 yago_plan_qty_ton_mtd,
0 yago_plan_qty_ton_ytd,
0 yago_plan_qty_box,
0 yago_plan_qty_box_mtd,
0 yago_plan_qty_box_ytd,
0 yago_plan_amt_bf_no_tax,
0 yago_plan_amt_bf_no_tax_mtd,
0 yago_plan_amt_bf_no_tax_ytd,
0 yago_plan_amt_af_no_tax,
0 yago_plan_amt_af_no_tax_mtd,
0 yago_plan_amt_af_no_tax_ytd,
0 yago_task_qty_ton,
0 yago_task_qty_ton_mtd,
0 yago_task_qty_ton_ytd,
0 yago_task_qty_ton_ytd_all,
0 yago_task_qty_box,
0 yago_task_qty_box_mtd,
0 yago_task_qty_box_ytd,
0 yago_task_qty_box_ytd_all,
0 yago_task_amt_bf_no_tax,
0 yago_task_amt_bf_no_tax_mtd,
0 yago_task_amt_bf_no_tax_ytd,
0 yago_task_amt_bf_no_tax_ytd_all,
0 yago_task_amt_af_no_tax,
0 yago_task_amt_af_no_tax_mtd,
0 yago_task_amt_af_no_tax_ytd,
0 yago_task_amt_af_no_tax_ytd_all,
0 yago_budget_qty_ton,
0 yago_budget_qty_ton_mtd,
0 yago_budget_qty_ton_ytd,
0 yago_budget_qty_ton_ytd_all,
0 yago_budget_qty_box,
0 yago_budget_qty_box_mtd,
0 yago_budget_qty_box_ytd,
0 yago_budget_qty_box_ytd_all,
0 yago_budget_amt_bf_without_tax,
0 yago_budget_amt_bf_without_tax_mtd,
0 yago_budget_amt_bf_without_tax_ytd,
0 yago_budget_amt_bf_without_tax_ytd_all,
0 yago_budget_amt_af_without_tax,
0 yago_budget_amt_af_without_tax_mtd,
0 yago_budget_amt_af_without_tax_ytd,
0 yago_budget_amt_af_without_tax_ytd_all,
0 tmago_sales_qty_ton,
0 tmago_sales_qty_ton_mtd,
0 tmago_sales_qty_ton_ytd,
0 tmago_sales_qty_box,
0 tmago_sales_qty_box_mtd,
0 tmago_sales_qty_box_ytd,
0 tmago_sales_amt_before,
0 tmago_sales_amt_before_mtd,
0 tmago_sales_amt_before_ytd,
0 tmago_sales_amt_after,
0 tmago_sales_amt_after_mtd,
0 tmago_sales_amt_after_ytd,
0 tmago_amt_bf_without_tax,
0 tmago_amt_bf_without_tax_mtd,
0 tmago_amt_bf_without_tax_ytd,
0 tmago_amt_af_without_tax,
0 tmago_amt_af_without_tax_mtd,
0 tmago_amt_af_without_tax_ytd,
0 plan_amt_before,
0 plan_amt_before_mtd,
0 plan_amt_before_ytd,
0 plan_amt_after,
0 plan_amt_after_mtd,
0 plan_amt_after_ytd,
0 task_amt_before,
0 task_amt_before_mtd,
0 task_amt_before_ytd,
0 task_amt_before_ytd_all,
0 task_amt_after,
0 task_amt_after_mtd,
0 task_amt_after_ytd,
0 task_amt_after_ytd_all,
0 budget_amt_before,
0 budget_amt_before_mtd,
0 budget_amt_before_ytd,
0 budget_amt_before_ytd_all,
0 budget_amt_after,
0 budget_amt_after_mtd,
0 budget_amt_after_ytd,
0 budget_amt_after_ytd_all,
0 yago_plan_amt_before,
0 yago_plan_amt_before_mtd,
0 yago_plan_amt_before_ytd,
0 yago_plan_amt_after,
0 yago_plan_amt_after_mtd,
0 yago_plan_amt_after_ytd,
0 yago_task_amt_before,
0 yago_task_amt_before_mtd,
0 yago_task_amt_before_ytd,
0 yago_task_amt_before_ytd_all,
0 yago_task_amt_after,
0 yago_task_amt_after_mtd,
0 yago_task_amt_after_ytd,
0 yago_task_amt_after_ytd_all,
0 yago_budget_amt_before,
0 yago_budget_amt_before_mtd,
0 yago_budget_amt_before_ytd,
0 yago_budget_amt_before_ytd_all,
0 yago_budget_amt_after,
0 yago_budget_amt_after_mtd,
0 yago_budget_amt_after_ytd,
0 yago_budget_amt_after_ytd_all,
0 mago_plan_amt_before,
0 mago_plan_amt_before_mtd,
0 mago_plan_amt_before_ytd,
0 mago_plan_amt_after,
0 mago_plan_amt_after_mtd,
0 mago_plan_amt_after_ytd,
0 mago_task_amt_before,
0 mago_task_amt_before_mtd,
0 mago_task_amt_before_ytd,
0 mago_task_amt_before_ytd_all,
0 mago_task_amt_after,
0 mago_task_amt_after_mtd,
0 mago_task_amt_after_ytd,
0 mago_task_amt_after_ytd_all,
0 mago_budget_amt_before,
0 mago_budget_amt_before_mtd,
0 mago_budget_amt_before_ytd,
0 mago_budget_amt_before_ytd_all,
0 mago_budget_amt_after,
0 mago_budget_amt_after_mtd,
0 mago_budget_amt_after_ytd,
0 mago_budget_amt_after_ytd_all,
0 tmago_plan_amt_before,
0 tmago_plan_amt_before_mtd,
0 tmago_plan_amt_before_ytd,
0 tmago_plan_amt_after,
0 tmago_plan_amt_after_mtd,
0 tmago_plan_amt_after_ytd,
0 tmago_task_amt_before,
0 tmago_task_amt_before_mtd,
0 tmago_task_amt_before_ytd,
0 tmago_task_amt_before_ytd_all,
0 tmago_task_amt_after,
0 tmago_task_amt_after_mtd,
0 tmago_task_amt_after_ytd,
0 tmago_task_amt_after_ytd_all,
0 tmago_budget_amt_before,
0 tmago_budget_amt_before_mtd,
0 tmago_budget_amt_before_ytd,
0 tmago_budget_amt_before_ytd_all,
0 tmago_budget_amt_after,
0 tmago_budget_amt_after_mtd,
0 tmago_budget_amt_after_ytd,
0 tmago_budget_amt_after_ytd_all,
1 complete_percent_target,
cast(substr(d.day_id,1,4) as bigint) as sales_year,
substr(d.day_id,1,6) as date_
 from (select row_wid day_id from bigdata_dw.w_date_d where dt_type='D' and row_wid>=cast(regexp_replace(trunc(add_months(date_sub(current_date,1),-1),'MM'),'-','') as bigint) and row_wid<=cast(regexp_replace(last_day(date_sub(current_date,1)),'-','') as bigint)) d
left join (select 
area as sale_area_name,
prod_desc as pro_categ_name,
year_month as mon_id,
cast(if(tax_amt='',0,nvl(tax_amt,0)) as bigint )*10000 as task_amt_before
from datalake_md.fact_ec_budget_plan where src_identity='SI' and year_month >=substr(regexp_replace(trunc(add_months(date_sub(current_date,1),-1),'MM'),'-',''),1,6) and year_month <=regexp_replace(substr(date_sub(current_date,1),1,7),'-','')) b
on substr(d.day_id,1,6) = b.mon_id
left join (select distinct platform_name,sale_area_name as sale_area_name1,final_name as sale_area_name from bigdata_dw.w_ec_area_d_tmp where platform_type = 'SI') c
on b.sale_area_name = c.sale_area_name1
where b.mon_id is not null;

--步骤2
insert overwrite table bigdata_dm.pj_ec_sales_si partition(date_)
select * from bigdata_dm.pj_ec_sales_si_mtd_tmp where date_>=regexp_replace(substr(add_months(date_sub(current_date,1),-1),1,7),'-','');

truncate table bigdata_dm.dm_ec_sales_dim_for_gmv_appfilter;
insert overwrite table  bigdata_dm.dm_ec_sales_dim_for_gmv_appfilter
select distinct gmv.platform_name
,gmv.sale_area_name
,gmv.pro_categ_name
,gmv.pro_brand_name
from bigdata_dm.pj_ec_sales_gmv gmv
where date_ >= '201801'
sort by gmv.platform_name
,gmv.sale_area_name
,gmv.pro_categ_name
,gmv.pro_brand_name;

truncate table bigdata_dm.dm_ec_sales_dim_for_si_appfilter;
insert overwrite table  bigdata_dm.dm_ec_sales_dim_for_si_appfilter
select distinct si.platform_name
,si.sale_area_name
,si.pro_categ_name
,si.pro_brand_name
from bigdata_dm.pj_ec_sales_si si
where date_ >= '201801'
sort by si.platform_name
,si.sale_area_name
,si.pro_categ_name
,si.pro_brand_name;